INSERT INTO Event(Ename, Dname) VALUES ('+ 97kg (heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('54 - 59kg, total (bantamweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('- 66.6kg (lightweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('60 - 63.5kg (light-welterweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('fixed bird target large birds teams', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('individual', 'Jumping');
INSERT INTO Event(Ename, Dname) VALUES ('olympic class monotype', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('54 - 57kg (featherweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('épée, amateurs and masters', 'Fencing');
INSERT INTO Event(Ename, Dname) VALUES ('sprint', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('82 - 90kg (light-heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('board (division II)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('softball', 'Softball');
INSERT INTO Event(Ename, Dname) VALUES ('Tornado - Multihull', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('Olympic Sprint', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('61 - 67kg (lightweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('76 - 85kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('team, portable apparatus', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('lightweight double sculls (2x)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('4000m steeplechase', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('50y freestyle (45.72m)', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('52 - 57kg (lightweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('68 - 80kg (middleweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('shot put, both hands', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('+ 80kg (heavyweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('100m running deer, single shots', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('C-2 (canoe double)', 'Canoe / Kayak S');
INSERT INTO Event(Ename, Dname) VALUES ('4000m freestyle', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('60 - 67.5kg, one-two hand 5 events (lightweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('12 foot dinghy', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('cesta punta', 'Basque Pelota');
INSERT INTO Event(Ename, Dname) VALUES ('90 - 100kg (heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('- 52kg (flyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('300+600m free rifle, team, prone', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('water polo', 'Water polo');
INSERT INTO Event(Ename, Dname) VALUES ('+ 78kg (heavyweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('63 - 70kg (half-middleweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('600m free rifle, prone', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('1500m freestyle', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('66 - 72kg (half-heavyweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('91 - 110kg, total (heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('60 - 67.5kg, total (lightweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('épée individual', 'Fencing');
INSERT INTO Event(Ename, Dname) VALUES ('épée, masters', 'Fencing');
INSERT INTO Event(Ename, Dname) VALUES ('K-4 500m (kayak four)', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('ice hockey', 'Ice Hockey');
INSERT INTO Event(Ename, Dname) VALUES ('500m time trial', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('+ 82.5kg, one-two hand 5 events (heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('67.5 - 75kg (middleweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('long jump individual', 'Jumping');
INSERT INTO Event(Ename, Dname) VALUES ('50m small bore rifle, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('au cordon doré, 50m', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('individual road race', 'Cycling Road');
INSERT INTO Event(Ename, Dname) VALUES ('50.8 - 53.52kg (bantamweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('600m free rifle', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('individual time trial', 'Cycling Road');
INSERT INTO Event(Ename, Dname) VALUES ('+ 80kg (heavyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('+ 91kg (super heavyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('moving bird target 50m teams', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('Sprint indivual', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('66 - 74kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('double american round (60y - 50y - 40y)', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('61.24 - 66.68kg (welterweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('triathlon (long jump / shot put / 100 yards)', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('moving bird target, 28m', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('90 - 100kg, total (first-heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('57 - 60kg (lightweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('1/4 mile (402.3m)', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('100 - 110kg, total (heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('50m running target (30+30 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('58 - 63kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('- 60kg, total (featherweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('8m (rating 1907)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('75 - 82.5kg, one-two hand 5 e. (light-heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('75 - 82.5kg, total (light-heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('mixed doubles', 'Tennis');
INSERT INTO Event(Ename, Dname) VALUES ('- 48 kg', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('cross-country', 'Mountain Bike');
INSERT INTO Event(Ename, Dname) VALUES ('Individual', 'Triathlon');
INSERT INTO Event(Ename, Dname) VALUES ('hammer throw', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('RS:X - Windsurfer', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('6.5m (rating 1919)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('C-1 1000m (canoe single)', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('400m hurdles', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('rifle, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('long jump', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('individual 1 ball', 'Croquet');
INSERT INTO Event(Ename, Dname) VALUES ('6m (rating 1907)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('70 - 78kg (welterweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('50m rifle prone (60 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('- 60kg, one-two hand 3 events (featherweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('4miles team', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('48 - 52kg (flyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('Finn - Heavyweight Dinghy', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('3-10t', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('3000m walk', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('105kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('25m army pistol', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('foil team', 'Fencing');
INSERT INTO Event(Ename, Dname) VALUES ('48 - 54kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('lacrosse', 'Lacrosse');
INSERT INTO Event(Ename, Dname) VALUES ('58kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('3000m team', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('100m running deer, single shots, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('army rifle, 300m, kneeling', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('67 - 73kg (welterweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('cricket', 'Cricket');
INSERT INTO Event(Ename, Dname) VALUES ('76 - 83kg, total (light-heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('57.15 - 63.5kg (lightweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('63 - 69kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('200m individual medley', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('C-1 500m (canoe single)', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('52 - 57kg (bantamweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('30m army pistol, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('58 - 60kg (featherweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('65 - 71kg (lightweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('4x400m relay', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('5000m', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('58 - 63kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('48 - 55kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('49 - 57 kg', 'Taekwondo');
INSERT INTO Event(Ename, Dname) VALUES ('81 - 91kg (heavyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('board (windglider)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('100m hurdles', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('80m hurdles', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('48 - 52kg (half-lightweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('- 49 kg', 'Taekwondo');
INSERT INTO Event(Ename, Dname) VALUES ('100m running deer, double shots', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('+ 79.38kg (heavyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('folding K-1 10000m', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('71 - 78kg (half-middleweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('Star - Keelboat', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('10-20t', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('57 - 63kg (half-middleweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('au cordon doré, 33m', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('60 - 67.5kg, one-two hand 3 events (lightweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('56 - 60kg, total (featherweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('200m breaststroke', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('56.7 - 61.23kg (featherweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('doubles', 'Table Tennis');
INSERT INTO Event(Ename, Dname) VALUES ('board (Mistral)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('65.77 - 71.67kg (middleweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('moving bird target 28m teams', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('3200m steeplechase', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('foil individual', 'Fencing');
INSERT INTO Event(Ename, Dname) VALUES ('C-2 10000m', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('63kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('individual FITA round', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('shot put', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('78 - 86kg (middleweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('10m platform', 'Diving');
INSERT INTO Event(Ename, Dname) VALUES ('underwater swimming', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('skeet (75 targets)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('100 - 130kg (super heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('97 - 130kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('400m individual medley', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('trap (125 targets)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('71-75kg', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('single sculls (1x)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('K-1 10000m', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('singles', 'Badminton');
INSERT INTO Event(Ename, Dname) VALUES ('60 - 65kg (half-lightweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('open class', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('2 miles (3.218km)', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('57.15 - 61.24kg (lightweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('army rifle, 300m', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('7m', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('individual', 'Trampoline');
INSERT INTO Event(Ename, Dname) VALUES ('100m running deer, double shots, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('63.5 - 71.67kg (middleweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('individual', 'Roque');
INSERT INTO Event(Ename, Dname) VALUES ('swallow (golondrina)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('continental style 50m', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('special figures', 'Figure skating');
INSERT INTO Event(Ename, Dname) VALUES ('69 - 75 kg', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('doubles', 'Badminton');
INSERT INTO Event(Ename, Dname) VALUES ('25m small rifle', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('47.6 - 52.16kg (flyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('50y army pistol, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('82.5 - 90kg, total (middle-heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('60.3 - 66.6kg (lightweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('- 60kg, one-two hand 5 events (featherweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('+ 82.5kg (super heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('C-2 1000m (canoe double)', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('- 48kg (light-flyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('+ 105kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('team', 'Golf');
INSERT INTO Event(Ename, Dname) VALUES ('73 - 81kg (half-middleweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('63 - 67kg (lightweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('4x100m freestyle relay', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('6m (rating 1919)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('basketball', 'Basketball');
INSERT INTO Event(Ename, Dname) VALUES ('individual', 'Dressage');
INSERT INTO Event(Ename, Dname) VALUES ('53.52 - 57.15kg (featherweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('fixed bird target small bird, teams', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('solo', 'Synchronized S.');
INSERT INTO Event(Ename, Dname) VALUES ('57 - 62kg (featherweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('58 - 62kg (lightweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('40m sq', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('57 - 61kg (featherweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('K-4 1000m (kayak four)', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('50m rifle 3 positions (3x20 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('66 - 72kg (welterweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('8m', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('Team Pursuit (4000m)', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('60m', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('combined 4 events', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('- 60kg (featherweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('pair-oared shell with coxswain (2+)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('100m breaststroke', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('25m rapid fire pistol (60 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('individual', 'Golf');
INSERT INTO Event(Ename, Dname) VALUES ('team, Swedish system', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('400m breaststroke', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('national round (60y - 50y)', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('66.6 - 73kg (middleweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('74 - 84kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('10m air pistol (60 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('1200m freestyle', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('four without coxswain (4-)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('55 - 63kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('4x100m medley relay', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('+ 97kg (super heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('army rifle, 300m, 3 positions', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('team (FITA Olympic round - 70m)', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('- 58 kg', 'Taekwondo');
INSERT INTO Event(Ename, Dname) VALUES ('70 - 76kg, total (middleweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('stick, single', 'Fencing');
INSERT INTO Event(Ename, Dname) VALUES ('10000m', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('54 - 58kg (featherweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('Keirin', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('plunge for distance', 'Diving');
INSERT INTO Event(Ename, Dname) VALUES ('56 - 61kg (featherweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('10000m walk', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('400m', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('68 - 74kg (welterweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('6m', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('100m backstroke', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('C-1 10000m', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('balance beam', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('coxless pair (2-)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('84 - 96kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('baseball', 'Baseball');
INSERT INTO Event(Ename, Dname) VALUES ('mixed doubles indoor', 'Tennis');
INSERT INTO Event(Ename, Dname) VALUES ('400m freestyle', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('67.5 - 75kg, one-two hand 3 events (middleweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('folding K-2 10000m', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('50m rifle 3 positions (3x40 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('sabre team', 'Fencing');
INSERT INTO Event(Ename, Dname) VALUES ('uneven bars', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('- 55kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('Laser - One Person Dinghy', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('80 - 93kg (half-heavyweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('63 - 69kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('300m free rifle, standing, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('open category', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('javelin throw', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('87 - 97kg (light-heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('25m pistol (30+30 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('synchronized diving 10m platform', 'Diving');
INSERT INTO Event(Ename, Dname) VALUES ('87 - 97kg (light-heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('84 - 96kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('200m obstacle event', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('hockey', 'Hockey');
INSERT INTO Event(Ename, Dname) VALUES ('eight with coxswain (8+)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('moving bird target, 50m', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('team competition', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('72 - 79kg (middleweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('team', 'Jumping');
INSERT INTO Event(Ename, Dname) VALUES ('+ 95kg (heavyweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('sabre, masters', 'Fencing');
INSERT INTO Event(Ename, Dname) VALUES ('1/3 mile (536.5m)', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('board (lechner)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('63 - 72kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('82 - 90kg (light-heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('singles', 'Tennis');
INSERT INTO Event(Ename, Dname) VALUES ('1000y free rifle, prone', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('66.6 - 73kg (middleweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('- 68kg (lightweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('+ 67 kg', 'Taekwondo');
INSERT INTO Event(Ename, Dname) VALUES ('69 - 76kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('Yngling - Keelboat', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('96 - 120kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('200m team swimming', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('48 - 52kg (flyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('- 56kg, total (bantamweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('team time trial', 'Cycling Road');
INSERT INTO Event(Ename, Dname) VALUES ('5 miles (8047m)', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('individual', 'Eventing');
INSERT INTO Event(Ename, Dname) VALUES ('- 48kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('team', 'Eventing');
INSERT INTO Event(Ename, Dname) VALUES ('- 56kg (bantamweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('discus throw ancient style', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('- 56kg (bantamweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('tug of war', 'Tug of War');
INSERT INTO Event(Ename, Dname) VALUES ('57 - 63kg (featherweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('3000m', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('+ 100kg (heavyweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('63 - 70kg (lightweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('20km race walk', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('8m (rating 1919)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('100m butterfly', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('trap (75 targets)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('polo', 'Polo');
INSERT INTO Event(Ename, Dname) VALUES ('double york round (100y - 80y - 60y)', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('4x200m freestyle relay', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('200m backstroke', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('+ 80 kg', 'Taekwondo');
INSERT INTO Event(Ename, Dname) VALUES ('3000m steeplechase', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('10m', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('67 - 73kg (middleweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('york round (100y - 80y - 60y)', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('50km walk', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('Individual Pursuit', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('tempest', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('teams FITA round', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('One lap (660y) sprint', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('70 - 80kg (middleweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('200m butterfly', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('62 - 67kg (welterweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('Laser Radial - One Person Dinghy', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('4x50y freestyle relay', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('- 52kg (flyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('61.23 - 65.77kg (lightweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('- 55kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('rope climbing', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('- 52kg, total (flyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('team, parallel bars', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('66 - 72kg (welterweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('cross country individual', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('52.62 - 57.15kg (featherweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('50+100y small bore rifle, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('74 - 82kg (middleweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('73 - 79kg (middleweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('fixed bird target small birds', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('50km', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('47.63 - 52.16kg (bantamweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('60 - 66kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('20km walk', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('football', 'Football');
INSERT INTO Event(Ename, Dname) VALUES ('class B up to 60 feet', 'Water Motorspor');
INSERT INTO Event(Ename, Dname) VALUES ('54 - 60.3kg (featherweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('75 - 81kg (light-heavyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('épée team', 'Fencing');
INSERT INTO Event(Ename, Dname) VALUES ('fixed bird target large birds', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('quadruple sculls without coxswain (4x)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('54 - 57.15kg (featherweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('- 54kg, total (flyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('vault', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('56.7 - 61.24kg (lightweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('55 - 60kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('individual', 'Figure skating');
INSERT INTO Event(Ename, Dname) VALUES ('cross country team', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('quadruple sculls with coxswain (4x)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('Individual', 'BMX');
INSERT INTO Event(Ename, Dname) VALUES ('300m free rifle, prone, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('javelin throw freestyle', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('74 - 84kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('volleyball', 'Volleyball');
INSERT INTO Event(Ename, Dname) VALUES ('floor exercises', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('decathlon', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('70 - 78kg (welterweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('- 58kg (bantamweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('58 - 62kg (featherweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('coxless four (4-)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('10km', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('200m freestyle', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('pairs', 'Figure skating');
INSERT INTO Event(Ename, Dname) VALUES ('singles indoor', 'Tennis');
INSERT INTO Event(Ename, Dname) VALUES ('10m (rating 1907)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('66 - 74kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('12m (rating 1919)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('+ 87kg (heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('470 - Two Person Dinghy', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('85kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('55 - 60kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('double', 'Rackets');
INSERT INTO Event(Ename, Dname) VALUES ('- 51kg (flyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('86 - 95kg (half-heavyweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('100m freestyle', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('open event', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('+ 82.5kg, one-two hand 3 events (heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('67 - 71kg (light-middleweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('beach volleyball', 'Beach volley.');
INSERT INTO Event(Ename, Dname) VALUES ('97 - 130kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('individual', 'BMX');
INSERT INTO Event(Ename, Dname) VALUES ('12m', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('50.8 - 54kg (bantamweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('sur la perche à la herse', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('49er - Skiff', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('1 mile (1609.3m)', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('72 - 79kg (middleweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('18 foot dinghy', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('- 50.8kg (flyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('67.5 - 75kg, total (middleweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('two-person keelboat open (Star)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('K-2 500m (kayak double)', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('double columbia round (50y - 40y - 30y)', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('Team Sprint', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('+ 72kg (heavyweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('10m air rifle (40 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('880y freestyle (804.66m)', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('Individual competition', 'Modern Pentath.');
INSERT INTO Event(Ename, Dname) VALUES ('- 52.62kg (bantamweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('4x100m relay', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('56 - 61kg (featherweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('69kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('60 - 67.5kg (lightweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('56 - 61kg (half-middleweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('- 54kg (bantamweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('Madison', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('C-1 (canoe single)', 'Canoe / Kayak S');
INSERT INTO Event(Ename, Dname) VALUES ('figure riding team', 'Vaulting');
INSERT INTO Event(Ename, Dname) VALUES ('triple jump, standing', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('30m sq', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('64 - 70kg, total (lightweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('48 - 51kg (flyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('64 - 69 kg', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('400, 600, 800m free rifle, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('72.57 - 79.38kg (light-heavyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('parallel bars', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('600m free rifle, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('10m air pistol (40 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('54 - 58kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('- 47.63kg (flyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('52.16 - 56.7kg (featherweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('50m pistol (60 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('C-2 500m (canoe double)', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('74 - 82kg (middleweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('5000m', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('Team competition', 'Modern Pentath.');
INSERT INTO Event(Ename, Dname) VALUES ('75kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('60 - 67.5kg (lightweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('75 - 82.5kg, one-two hand 3 e. (light-heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('200m hurdles', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('+ 80kg (heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('12m (rating 1907)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('10m air rifle (60 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('51 - 54kg (bantamweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('25 miles (40.232km)', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('sur la perche à la pyramide', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('skeet (125 targets)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('61 - 66kg (middleweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('57 - 63kg (featherweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('5 miles (8.046km)', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('5.5m', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('marathon 10km', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('double trap (150 targets)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('96 - 120kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('team', 'Table Tennis');
INSERT INTO Event(Ename, Dname) VALUES ('heavyweight - one hand lift', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('1km time trial', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('62kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('76 - 85kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('double national round (60y - 50y)', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('61 - 66kg (lightweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('open class A', 'Water Motorspor');
INSERT INTO Event(Ename, Dname) VALUES ('lightweight coxless four (4-)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('doubles', 'Tennis');
INSERT INTO Event(Ename, Dname) VALUES ('2000m tandem', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('discus throw', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('high jump', 'Jumping');
INSERT INTO Event(Ename, Dname) VALUES ('+ 90kg, total (heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('1/2 mile (804.7m)', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('plain high diving', 'Diving');
INSERT INTO Event(Ename, Dname) VALUES ('+ 108kg, total (super heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('25y small bore rifle, moving target', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('61 - 66kg (lightweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('- 48kg (light-flyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('singles', 'Table Tennis');
INSERT INTO Event(Ename, Dname) VALUES ('clay pigeons, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('individual all-round', 'Rhythmic G.');
INSERT INTO Event(Ename, Dname) VALUES ('58 - 68 kg', 'Taekwondo');
INSERT INTO Event(Ename, Dname) VALUES ('+ 81kg (heavyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('K-1 500m (kayak single)', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('individual', 'Jeu de Paume');
INSERT INTO Event(Ename, Dname) VALUES ('67 - 73kg (welterweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('figure riding individual', 'Vaulting');
INSERT INTO Event(Ename, Dname) VALUES ('78 - 87kg (middleweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('52 - 57kg (bantamweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('horizontal bar', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('heavyweight - two hand lift', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('sharpie 12m2', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('flying dutchman', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('54 - 58kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('60 - 66kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('firefly class', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('team', 'Dressage');
INSERT INTO Event(Ename, Dname) VALUES ('61.24 - 65.77kg (welterweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('indian clubs', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('79 - 87kg (light-heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('25y small bore rifle, disappearing target', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('10m (rating 1919)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('single-handed dinghy open (Laser)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('+ 73kg (heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('99 - 108kg, total (heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('3m springboard', 'Diving');
INSERT INTO Event(Ename, Dname) VALUES ('57 - 67 kg', 'Taekwondo');
INSERT INTO Event(Ename, Dname) VALUES ('66.68 - 72.57kg (middleweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('high jump, standing', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('- 48kg (extra-lightweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('+ 71.67kg (heavyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('doubles indoor', 'Tennis');
INSERT INTO Event(Ename, Dname) VALUES ('3miles team (4828m)', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('+ 71.67kg (heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('synchronized diving 3m springboard', 'Diving');
INSERT INTO Event(Ename, Dname) VALUES ('200m', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('56lb weight throw (25.4kg)', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('90 - 100kg (heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('double', 'Croquet');
INSERT INTO Event(Ename, Dname) VALUES ('75 - 80kg (light-heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('59 - 64kg, total (featherweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('K-2 10000m', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('65.77 - 71.67kg (welterweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('52 - 56kg (lightweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('5000m team', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('all-around Dumbbell contest', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('K-1 1000m (kayak single)', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('77kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('individual', 'Rackets');
INSERT INTO Event(Ename, Dname) VALUES ('coxed fours Jugriggers', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('60 - 66kg (half-lightweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('triple jump', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('individual pursuit', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('sabre individual', 'Fencing');
INSERT INTO Event(Ename, Dname) VALUES ('8m class C', 'Water Motorspor');
INSERT INTO Event(Ename, Dname) VALUES ('48 - 54kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('group competition', 'Rhythmic G.');
INSERT INTO Event(Ename, Dname) VALUES ('56kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('dragon', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('double trap (120 targets)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('+ 87kg (super heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('individual all-round', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('marathon', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('army rifle, 300m, standing', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('110m hurdles', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('moving bird target 33m teams', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('73 - 80kg (light-heavyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('25m small bore rifle, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('combined 3 events', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('Points Race', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('70 - 78kg (half-heavyweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('- 47.6kg (light-flyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('62 - 68kg (lightweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('single-handed dinghy (Finn)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('club swinging', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('K-1 4x500m', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('300m free rifle 3 positions (3x40 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('army rifle, 300m, prone', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('79 - 87kg (light-heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('66 - 73kg (lightweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('discus throw, both hands', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('62 - 68kg (lightweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('100m freestyle for sailors', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('rugby', 'Rugby');
INSERT INTO Event(Ename, Dname) VALUES ('rings', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('83 - 91kg, total (middle-heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('handball', 'Handball');
INSERT INTO Event(Ename, Dname) VALUES ('pommel horse', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('67.5 - 75kg, one-two hand 5 events (middleweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('85 - 97kg', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('63 - 70kg (middleweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('1500m', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('100km', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('team round 60y', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('68 - 80 kg', 'Taekwondo');
INSERT INTO Event(Ename, Dname) VALUES ('army rifle, 200m', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('73 - 93kg (light-heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('heptathlon', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('60 - 64 kg', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('12 foot dinghy individual', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('moving bird target, 33m', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('free rifle, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('single-handed dinghy (Europe)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('10miles walk (16093m)', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('fleet/match race keelboat open (Soling)', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('75 - 82.5kg (light-heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('tumbling', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('0.5-1t', 'Sailing');
INSERT INTO Event(Ename, Dname) VALUES ('- 60kg (featherweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('- 48kg (light-flyweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('100m running deer, single/double shots', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('91 - 99kg, total (first-heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('individual (FITA Olympic round - 70m)', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('Sidehorse vault', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('68 - 74kg (welterweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('100m', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('+ 93kg (super heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('48kg (light flywieght)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('+ 75kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('67.5 - 75kg (middleweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('63 - 70kg (lightweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('points race', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('+ 110kg, total (super heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('800m', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('90 - 100kg (half-heavyweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('- 63kg (lightweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('- 60 kg', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('12-hour race', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('au chapelet, 33m', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('four-oared shell with coxswain (4-)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('50m army pistol, team', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('high jump', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('10m running target (30+30 shots)', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('25 kilometres', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('50m freestyle', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('duet', 'Synchronized S.');
INSERT INTO Event(Ename, Dname) VALUES ('52 - 56kg, total (bantamweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('team, horizontal bar', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('team', 'Synchronized S.');
INSERT INTO Event(Ename, Dname) VALUES ('48kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('pentathlon', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('+ 82.5kg, total (heavyweight)', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('85 - 97kg', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('73 - 79kg (middleweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('foil, masters', 'Fencing');
INSERT INTO Event(Ename, Dname) VALUES ('3500m walk', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('78 - 87kg (middleweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('pair without coxswain (2-)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('K-2 1000m (kayak double)', 'Canoe / Kayak F');
INSERT INTO Event(Ename, Dname) VALUES ('81 - 90kg (middleweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('+ 100kg (super heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('100 - 130kg (super heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('pole vault', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('75 - 82kg (light-heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('52.16 - 56.7kg (bantamweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('50m small bore rifle, standing, individual', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('94kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('63.5 - 67kg (welterweight)', 'Boxing');
INSERT INTO Event(Ename, Dname) VALUES ('javelin throw, both hands', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('K-1 (kayak single)', 'Canoe / Kayak S');
INSERT INTO Event(Ename, Dname) VALUES ('20km', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('1980 yards Pursuit, Team', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('800m freestyle', 'Swimming');
INSERT INTO Event(Ename, Dname) VALUES ('+ 93kg (heavyweight)', 'Judo');
INSERT INTO Event(Ename, Dname) VALUES ('individual 2 balls', 'Croquet');
INSERT INTO Event(Ename, Dname) VALUES ('+ 100kg (super heavyweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('au chapelet, 50m', 'Archery');
INSERT INTO Event(Ename, Dname) VALUES ('1km Pursuit', 'Cycling Track');
INSERT INTO Event(Ename, Dname) VALUES ('team, free system', 'Artistic G.');
INSERT INTO Event(Ename, Dname) VALUES ('600m free rifle, individual', 'Shooting');
INSERT INTO Event(Ename, Dname) VALUES ('57 - 62kg (featherweight)', 'Wrestling Free.');
INSERT INTO Event(Ename, Dname) VALUES ('+ 82kg (super heavyweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('double sculls (2x)', 'Rowing');
INSERT INTO Event(Ename, Dname) VALUES ('62 - 67.5kg (lightweight)', 'Wrestling Gre-R');
INSERT INTO Event(Ename, Dname) VALUES ('53kg', 'Weightlifting');
INSERT INTO Event(Ename, Dname) VALUES ('long jump, standing', 'Athletics');
INSERT INTO Event(Ename, Dname) VALUES ('69 - 76kg', 'Wrestling Free.');
