INSERT INTO Discipline(DName, Sports) VALUES ('Jumping', 'Equestrian');
INSERT INTO Discipline(DName, Sports) VALUES ('Taekwondo', 'Taekwondo');
INSERT INTO Discipline(DName, Sports) VALUES ('Vaulting', 'Equestrian');
INSERT INTO Discipline(DName, Sports) VALUES ('Synchronized S.', 'Aquatics');
INSERT INTO Discipline(DName, Sports) VALUES ('Basketball', 'Basketball');
INSERT INTO Discipline(DName, Sports) VALUES ('Cycling Track', 'Cycling');
INSERT INTO Discipline(DName, Sports) VALUES ('Archery', 'Archery');
INSERT INTO Discipline(DName, Sports) VALUES ('Hockey', 'Hockey');
INSERT INTO Discipline(DName, Sports) VALUES ('Table Tennis', 'Table Tennis');
INSERT INTO Discipline(DName, Sports) VALUES ('Cricket', 'Cricket');
INSERT INTO Discipline(DName, Sports) VALUES ('Figure skating', 'Skating');
INSERT INTO Discipline(DName, Sports) VALUES ('Canoe / Kayak S', 'Canoe / Kayak');
INSERT INTO Discipline(DName, Sports) VALUES ('Trampoline', 'Gymnastics');
INSERT INTO Discipline(DName, Sports) VALUES ('Croquet', 'Croquet');
INSERT INTO Discipline(DName, Sports) VALUES ('Baseball', 'Baseball');
INSERT INTO Discipline(DName, Sports) VALUES ('Boxing', 'Boxing');
INSERT INTO Discipline(DName, Sports) VALUES ('Jeu de Paume', 'Jeu de paume');
INSERT INTO Discipline(DName, Sports) VALUES ('Athletics', 'Athletics');
INSERT INTO Discipline(DName, Sports) VALUES ('Canoe / Kayak F', 'Canoe / Kayak');
INSERT INTO Discipline(DName, Sports) VALUES ('Rowing', 'Rowing');
INSERT INTO Discipline(DName, Sports) VALUES ('Eventing', 'Equestrian');
INSERT INTO Discipline(DName, Sports) VALUES ('Triathlon', 'Triathlon');
INSERT INTO Discipline(DName, Sports) VALUES ('Tennis', 'Tennis');
INSERT INTO Discipline(DName, Sports) VALUES ('Weightlifting', 'Weightlifting');
INSERT INTO Discipline(DName, Sports) VALUES ('Fencing', 'Fencing');
INSERT INTO Discipline(DName, Sports) VALUES ('Ice Hockey', 'Ice Hockey');
INSERT INTO Discipline(DName, Sports) VALUES ('Diving', 'Aquatics');
INSERT INTO Discipline(DName, Sports) VALUES ('Mountain Bike', 'Cycling');
INSERT INTO Discipline(DName, Sports) VALUES ('Badminton', 'Badminton');
INSERT INTO Discipline(DName, Sports) VALUES ('Judo', 'Judo');
INSERT INTO Discipline(DName, Sports) VALUES ('Softball', 'Softball');
INSERT INTO Discipline(DName, Sports) VALUES ('Sailing', 'Sailing');
INSERT INTO Discipline(DName, Sports) VALUES ('Swimming', 'Aquatics');
INSERT INTO Discipline(DName, Sports) VALUES ('Shooting', 'Shooting');
INSERT INTO Discipline(DName, Sports) VALUES ('Rugby', 'Rugby');
INSERT INTO Discipline(DName, Sports) VALUES ('Dressage', 'Equestrian');
INSERT INTO Discipline(DName, Sports) VALUES ('Lacrosse', 'Lacrosse');
INSERT INTO Discipline(DName, Sports) VALUES ('Beach volley.', 'Volleyball');
INSERT INTO Discipline(DName, Sports) VALUES ('Wrestling Gre-R', 'Wrestling');
INSERT INTO Discipline(DName, Sports) VALUES ('Rhythmic G.', 'Gymnastics');
INSERT INTO Discipline(DName, Sports) VALUES ('Basque Pelota', 'Basque Pelota');
INSERT INTO Discipline(DName, Sports) VALUES ('Rackets', 'Rackets');
INSERT INTO Discipline(DName, Sports) VALUES ('Handball', 'Handball');
INSERT INTO Discipline(DName, Sports) VALUES ('Volleyball', 'Volleyball');
INSERT INTO Discipline(DName, Sports) VALUES ('Cycling Road', 'Cycling');
INSERT INTO Discipline(DName, Sports) VALUES ('Tug of War', 'Tug of War');
INSERT INTO Discipline(DName, Sports) VALUES ('Water polo', 'Aquatics');
INSERT INTO Discipline(DName, Sports) VALUES ('Artistic G.', 'Gymnastics');
INSERT INTO Discipline(DName, Sports) VALUES ('Modern Pentath.', 'Modern Pentathlon');
INSERT INTO Discipline(DName, Sports) VALUES ('Golf', 'Golf');
INSERT INTO Discipline(DName, Sports) VALUES ('Polo', 'Polo');
INSERT INTO Discipline(DName, Sports) VALUES ('Wrestling Free.', 'Wrestling');
INSERT INTO Discipline(DName, Sports) VALUES ('BMX', 'Cycling');
INSERT INTO Discipline(DName, Sports) VALUES ('Roque', 'Roque');
INSERT INTO Discipline(DName, Sports) VALUES ('Football', 'Football');
INSERT INTO Discipline(DName, Sports) VALUES ('Water Motorspor', 'Water Motorsports');
