INSERT INTO Olympic_Game(Edition, City) VALUES (1980, 'Moscow');
INSERT INTO Olympic_Game(Edition, City) VALUES (1952, 'Helsinki');
INSERT INTO Olympic_Game(Edition, City) VALUES (1960, 'Rome');
INSERT INTO Olympic_Game(Edition, City) VALUES (2000, 'Sydney');
INSERT INTO Olympic_Game(Edition, City) VALUES (1896, 'Athens');
INSERT INTO Olympic_Game(Edition, City) VALUES (1948, 'London');
INSERT INTO Olympic_Game(Edition, City) VALUES (1932, 'Los Angeles');
INSERT INTO Olympic_Game(Edition, City) VALUES (1988, 'Seoul');
INSERT INTO Olympic_Game(Edition, City) VALUES (2004, 'Athens');
INSERT INTO Olympic_Game(Edition, City) VALUES (1936, 'Berlin');
INSERT INTO Olympic_Game(Edition, City) VALUES (1964, 'Tokyo');
INSERT INTO Olympic_Game(Edition, City) VALUES (1968, 'Mexico');
INSERT INTO Olympic_Game(Edition, City) VALUES (1908, 'London');
INSERT INTO Olympic_Game(Edition, City) VALUES (1984, 'Los Angeles');
INSERT INTO Olympic_Game(Edition, City) VALUES (1912, 'Stockholm');
INSERT INTO Olympic_Game(Edition, City) VALUES (1904, 'St Louis');
INSERT INTO Olympic_Game(Edition, City) VALUES (1924, 'Paris');
INSERT INTO Olympic_Game(Edition, City) VALUES (1920, 'Antwerp');
INSERT INTO Olympic_Game(Edition, City) VALUES (1976, 'Montreal');
INSERT INTO Olympic_Game(Edition, City) VALUES (1972, 'Munich');
INSERT INTO Olympic_Game(Edition, City) VALUES (1992, 'Barcelona');
INSERT INTO Olympic_Game(Edition, City) VALUES (1900, 'Paris');
INSERT INTO Olympic_Game(Edition, City) VALUES (2008, 'Beijing');
INSERT INTO Olympic_Game(Edition, City) VALUES (1928, 'Amsterdam');
INSERT INTO Olympic_Game(Edition, City) VALUES (1956, 'Melbourne / Stockholm');
INSERT INTO Olympic_Game(Edition, City) VALUES (1996, 'Atlanta');